# Generated by Django 5.1.7 on 2025-04-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rabble", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="interests",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.TextField(unique=True),
        ),
    ]
