# Generated by Django 4.2.20 on 2025-04-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rabble", "0003_rest_of_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="subrabbles",
            name="display_name",
            field=models.TextField(null=True),
        ),
    ]
