# Generated by Django 4.2.20 on 2025-05-08 04:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rabble", "0004_subrabbles_display_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="interests",
        ),
    ]
