# Generated by Django 4.2.20 on 2025-05-08 04:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rabble", "0005_remove_user_interests"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="communities",
            name="admin",
        ),
    ]
