# Generated by Django 4.2.20 on 2025-05-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rabble", "0006_remove_communities_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
