# Generated by Django 4.2.20 on 2025-05-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rabble", "0007_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
