# Generated by Django 4.2.20 on 2025-05-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rabble", "0008_alter_posts_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subrabbles",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
