# Generated by Django 4.2.20 on 2025-05-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rabble", "0009_alter_subrabbles_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="likes",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
